/* VIDEOS REDUCERS */
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const GET_MOVIE_PLAYING_SUCCESS = 'GET_MOVIE_PLAYING_SUCCESS';
export const GET_MOVIE_PLAYING_ERROR = 'GET_MOVIE_PLAYING_ERROR';

export const UPDATE_MOST_WATCHED_SUCCESS = 'UPDATE_MOST_WATCHED_SUCCESS';
export const UPDATE_MOST_WATCHED_ERROR = 'UPDATE_MOST_WATCHED_ERROR';

export const LOADING = 'LOADING';
export const RESET_MOVIES_STATE = 'RESET_MOVIES_STATE';
