/* PLAYLIST REDUCERS  */
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST';
export const GET_PLAYLIST_ERROR = 'GET_PLAYLIST_ERROR';

export const ADD_MOVIE_PLAYLIST = 'ADD_MOVIE_PLAYLIST';
export const ADD_MOVIE_PLAYLIST_ERROR = 'ADD_MOVIE_PLAYLIST_ERROR';

export const REMOVE_MOVIE_PLAYLIST = 'REMOVE_MOVIE_PLAYLIST';
export const REMOVE_MOVIE_PLAYLIST_ERROR = 'REMOVE_MOVIE_PLAYLIST_ERROR';

export const LOADING = 'LOADING';
