/* PLAYLIST REDUCERS  */
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST';
export const GET_PLAYLIST_ERROR = 'GET_PLAYLIST_ERROR';

export const ADD_VIDEO_PLAYLIST = 'ADD_VIDEO_PLAYLIST';
export const ADD_VIDEO_PLAYLIST_ERROR = 'ADD_VIDEO_PLAYLIST_ERROR';

export const REMOVE_VIDEO_PLAYLIST = 'REMOVE_VIDEO_PLAYLIST';
export const REMOVE_VIDEO_PLAYLIST_ERROR = 'REMOVE_VIDEO_PLAYLIST_ERROR';

export const LOADING = 'LOADING';
