/* VIDEOS REDUCERS */
export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_VIDEOS_ERROR = 'GET_VIDEOS_ERROR';

export const GET_VIDEO_PLAYING = 'GET_VIDEO_PLAYING';
export const GET_VIDEO_PLAYING_ERROR = 'GET_VIDEO_PLAYING_ERROR';

export const LOADING = 'LOADING';
